version: "3.9"
services:
  server:
    build: .
    container_name: jwt-learn
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - redis
    environment:
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
